openapi: 3.1.0
info:
  title: Domeo No-Code Calculators API
  version: 0.1.0
paths:
  /categories:
    get:
      summary: Список категорий
      responses:
        '200':
          description: OK
  /catalog/{category}/options:
    get:
      summary: Доступные значения атрибутов
      parameters:
        - in: path
          name: category
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /price/{category}:
    post:
      summary: Расчёт цены
      parameters:
        - in: path
          name: category
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
