version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: domeo
      POSTGRES_USER: domeo
      POSTGRES_PASSWORD: domeo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      PORT: 8080
      DB_CLIENT: pg
      PG_CONN: postgres://domeo:domeo@db:5432/domeo
      CONFIG_DIR: /app/config
      STATIC_DIR: /app/static
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  pgdata:
