FROM node:20-alpine AS deps
WORKDIR /app
COPY server/package.json server/tsconfig.json ./
RUN npm i --omit=dev && npm i -D typescript
COPY server/src ./src
COPY config ./config
COPY static ./static
RUN npx tsc -p .

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production PORT=8080 CONFIG_DIR=./config STATIC_DIR=./static DB_CLIENT=pg
COPY --from=deps /app/dist ./dist
COPY --from=deps /app/node_modules ./node_modules
EXPOSE 8080
CMD ["node","dist/index.js"]
